name: "Kill DPF Servers"
description: "Kill all running DPF Servers"
runs:
  using: "composite"
  steps:
    - name: Kill all servers
      shell: cmd
      run: |
        tasklist /FI "IMAGENAME eq Ans.Dpf.Grpc.exe" 2>NUL | find /I /N "Ans.Dpf.Grpc.exe">NUL
        ECHO %ERRORLEVEL%
        if "%ERRORLEVEL%"=="0"(taskkill /f /im Ans.Dpf.Grpc.exe)
