name: "Kill DPF Servers"
description: "Kill all running DPF Servers"
runs:
  using: "composite"
  steps:
    - name: "Kill all servers"
      shell: bash
      run: |
        echo $0
        if pgrep -x "Ans.Dpf.Grpc" > /dev/null
        then
            pkill -f Ans.Dpf.Grpc.exe || true
        fi        
