name: "Kill DPF Servers"
description: "Kills all running DPF Servers"
runs:
  using: "composite"
  steps:
    - name: "Kill all servers"
      shell: python
      run: |
        import psutil
        proc_name = "Ans.Dpf.Grpc"
        nb_procs = 0
        for proc in psutil.process_iter():
            # check whether the process name matches
            if proc_name in proc.name():
                try:
                  proc.kill()
                  nb_procs += 1
                except psutil.NoSuchProcess:
                  pass
        print(f"Killed {nb_procs} {proc_name} processes.")
