name: "Check licenses"
description: "Checks licenses of all installed packages in the current environment"
runs:
  using: "composite"
  steps:
    - name: "Check licences of packages"
      shell: bash
      run: |
        pip install pip-licenses
        pip-licenses
        pip uninstall -y pip-licenses
