name: "Generate documentation"
description: "Generates the documentation for the local DPF package"
inputs:
  python-version:
    description: "Python version"
    required: true
    default: "3.8"
  ANSYS_VERSION:
    description: "Ansys release version number in the format 221"
    required: true
  PACKAGE_NAME:
    description: "Package name"
    required: true
  MODULE:
    description: "Module name"
    required: true
    default: post
  dpf-standalone-TOKEN:
    description: "Token for DPF installation"
    required: true
  install_extras:
    description: "Extras to install for the local package"
    required: false
  build_extras:
    description: "Extra paths to build the doc for in the spinx-api command"
    required: false
  generate_pdf:
    description: "Whether to generate the PDF doc"
    required: false
    default: "True"

runs:
  using: "composite"
  steps:
    - name: "Setup Python"
      uses: actions/setup-python@v2.1.4
      with:
        python-version: ${{ inputs.python-version }}

    - name: "Install OS packages"
      shell: bash
      run: |
        sudo apt update
        sudo apt install pandoc texlive-latex-extra latexmk

    - name: "Install DPF"
      uses: pyansys/pydpf-actions/install-dpf-server@v2.2.dev1
      with:
        dpf-standalone-TOKEN: ${{inputs.dpf-standalone-TOKEN}}
        ANSYS_VERSION : ${{inputs.ANSYS_VERSION}}

    - name: "Install local package"
      uses: pyansys/pydpf-actions/install-package@v2.2.dev1

    - name: "Install extras"
      shell: bash
      run: |
        pip install .[${{inputs.install_extras}}]
      if: ${{inputs.install_extras}} != null

    - name: "Test import"
      shell: bash
      working-directory: tests
      run: python -c "from ansys.dpf import ${{inputs.MODULE}}"

    - name: "Setup headless display"
      uses: pyvista/setup-headless-display-action@v1

    - name: "Install documentation requirements"
      shell: bash
      run: |
        pip install -r requirements/requirements_docs.txt

    - name: "Build sphinx doc"
      shell: bash
      run: |
        export SPHINX_APIDOC_OPTIONS=inherited-members
        sphinx-apidoc -o docs/source/api ansys ${{inputs.build_extras}} -f --implicit-namespaces --separate --no-headings &>log_sphinx.txt

    - name: "Build HTML Documentation"
      shell: bash
      working-directory: docs
      run: |
        export TEMP=${{ runner.temp }}
        make clean
        echo "Making html doc..."
        make html &>log_html.txt

    - name: "Build PDF Documentation"
      shell: bash
      working-directory: docs
      if: ${{ inputs.generate_pdf == 'True' }}
      run: |
        export TEMP=${{ runner.temp }}
        echo "Making pdf doc..."
        make pdf &>log_pdf.txt

    - name: "Upload Documentation Build log"
      uses: actions/upload-artifact@v3
      with:
        name: doc-${{inputs.PACKAGE_NAME}}-log
        path: docs/*.txt
      if: always()

    - name: "Upload HTML Documentation"
      uses: actions/upload-artifact@v3
      with:
        name: HTML-doc-${{inputs.PACKAGE_NAME}}
        path: ./docs/build/html/*

    - name: "Upload PDF Documentation"
      uses: actions/upload-artifact@v3
      if: ${{ inputs.generate_pdf == 'True' }}
      with:
        name: PDF-doc-${{inputs.PACKAGE_NAME}}
        path: ./docs/build/latex/*.pdf

    - name: "Kill all servers"
      uses: pyansys/pydpf-actions/kill-dpf-servers@v2.2.dev1
