name: "Test docstrings of DPF Package"
description: "Test docstrings of DPF Package"
inputs:
  MODULE:
    description: "Module name"
    required: true
    default: post
  PACKAGE_NAME:
    description: "Package name"
    required: true
  working-directory:
    description: "Working-directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Set working directory"
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}

    - name: "Test API Docstrings"
      shell: bash
      run: |
        echo "TMP: "$TMP
        echo "TEMP: "$TEMP
        pytest --doctest-modules $DEBUG --junitxml=junit/test-doctests-results.xml src/ansys/dpf/${{inputs.MODULE}}

    - name: "Kill all servers"
      uses: pyansys/pydpf-actions/kill-dpf-servers@prepare_v2.2

    - name: "Upload Docstring Test Results"
      uses: actions/upload-artifact@v3.1.0
      with:
        name: ${{ inputs.PACKAGE_NAME }}_doctest
        path: junit/test-doctests-results.xml