name: "Prepare Testing environment for DPF Package"
description: "Prepare Testing environment for DPF Package"
inputs:
  DEBUG:
    description: "Debug print mode"
    required: true
    default: "false"
  working-directory:
    description: "Working-directory"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: "Set working directory"
      shell: bash
      run: |
        echo ${{ inputs.working-directory }}
        cd ${{ inputs.working-directory }}
        ls

    - name: "Setup headless display"
      uses: pyvista/setup-headless-display-action@v1

    - name: "Install Test Environment"
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: |
        pip install -r requirements/requirements_test.txt

    - name: "Set TMP"
      shell: bash
      run: |
        echo "TMP=${{ runner.temp }}" >> $GITHUB_ENV
        echo "TEMP=${{ runner.temp }}" >> $GITHUB_ENV

    - name: "Debug mode"
      shell: bash
      if: inputs.DEBUG == 'true'
      run: |
        echo "DEBUG=-v -s --durations=10 --durations-min=1.0" >> $GITHUB_ENV