name: "Install DPF Server"
description: "Install and test DPF Server for different OS and versions"
inputs:
  dpf-standalone-TOKEN:
    description: "github secret to access https://github.com/ansys-dpf/dpf-standalone"
    required: true
  ANSYS_VERSION:
    description: "Ansys release version number in the format 221"
    required: false
    default: "221"
outputs:
  SERVER:
    description: "Path to the server"
    value: ${{ steps.set-server-path.outputs.server-path }}
runs:
  using: "composite"
  steps:
    - name: "Checkout DPF Standalone repository"
      shell: pwsh
      run: |
        echo "OS: ${{ runner.os }}"
        echo "Ansys version: ${{ inputs.ANSYS_VERSION }}"

        $TEMP = ${{ inputs.ANSYS_VERSION }}
        $TEMP2 = $TEMP.ToString()
        $ANSYS_VERSION_WITH_POINT=$TEMP2.Insert(2,".")
        $BranchName = if ("${{ runner.os }}" -eq "Linux") { "linux_release-$ANSYS_VERSION_WITH_POINT" } else { "win_release-$ANSYS_VERSION_WITH_POINT" }
        git clone --branch $BranchName --single-branch https://${{ inputs.dpf-standalone-TOKEN }}@github.com/ansys-dpf/dpf-standalone

    - name: "Generate server path environment variable"
      shell: pwsh
      run: |
          if ("${{ runner.os }}" -eq "Linux")
          {
            $env:CURRENT_DIR = Get-Location
            echo "SERVER=$env:CURRENT_DIR/dpf-standalone"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          }
          else
          {
            $env:CURRENT_DIR = Get-Location
            echo "SERVER=$env:CURRENT_DIR\dpf-standalone"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
          }
     
    - name: "Setting action output"
      id: set-server-path
      shell: bash
      run: |
          echo "::set-output name=server-path::$(echo ${SERVER})"

    - name: "Generating AWP_ROOTXXX environment variable"
      shell: pwsh
      run: |
        echo "AWP_ROOT${{ inputs.ANSYS_VERSION }}=${{env.SERVER}}"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

    - name: "Setting DPF service"
      shell: pwsh
      run: |
        $SubFolder = if ("${{ runner.os }}" -eq "Linux") { "linx64" } else { "winx64" }
        echo "SubFolder=$SubFolder"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        cd ${{env.SERVER}}\aisol\bin\$SubFolder
        echo "List of files"
        ls .
        if ("${{ runner.os }}" -eq "Linux")
        {
          echo "Setting files permissions"
          chmod 755 Ans.Dpf.Grpc.sh
          chmod 755 Ans.Dpf.Grpc.exe
        }

    - name: "Launching DPF server"
      shell: pwsh
      run: |
        $SubFolder = if ("${{ runner.os }}" -eq "Linux") { "linx64" } else { "winx64" }
        $ToLaunch = if ("${{ runner.os }}" -eq "Linux") { "./Ans.Dpf.Grpc.sh" } else { "./Ans.Dpf.Grpc.bat" }

        cd ${{env.SERVER}}\aisol\bin\$env:SubFolder
        Start-Process -FilePath $ToLaunch -ArgumentList "--address 127.0.0.1" -RedirectStandardOutput "log.txt"

    - name: "Print log file"
      shell: pwsh
      run: |
        Get-Content -Path $env:SERVER\aisol\bin\$env:SubFolder\log.txt
