name: "Install DPF Server"
description: "Install and test DPF Server for different OS and versions"
inputs:
  dpf-standalone-TOKEN:
    description: "github secret to access https://github.com/ansys-dpf/dpf-standalone"
    required: true
  ANSYS_VERSION:
    description: "Ansys release version number in the format 22.1"
    required: false
    default: "22.1"
  ANSYS_VERSION_NO_POINT:
    description: "Ansys release version number in the format 221"
    required: false
    default: "221"
outputs:
  SERVER:
    description: "Path to the server"
    value: ${{ steps.set-server-path.outputs.server-path }}
runs:
  using: "composite"
  steps:
    - run: |
        echo ${process.platform}
        $BranchName = if (${runner.os} -eq "Linux") { "linux_release-${{inputs.ANSYS_VERSION }}" } else { "win_release-${{inputs.ANSYS_VERSION }}" }
        git clone --branch $BranchName --single-branch https://${{inputs.dpf-standalone-TOKEN}}@github.com/ansys-dpf/dpf-standalone
      shell: pwsh

    - run: echo "AWP_ROOT${{inputs.ANSYS_VERSION_NO_POINT}}=${{github.workspace}}\dpf-standalone"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - id: set-server-path
      run: echo "::set-output name=SERVER::$(echo AWP_ROOT$inputs:ANSYS_VERSION_NO_POINT)"
      shell: bash
      
    - run: echo "SERVER=${{github.workspace}}\dpf-standalone"  | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - run: |
        $SubFolder = if (${runner.os} -eq "Linux") { "linx64" } else { "winx64" }
        cd ${{env.SERVER}}\aisol\bin\$SubFolder
        ls .
        $ToLaunch = if (${runner.os} -eq "Linux") { "./Ans.Dpf.Grpc.sh" } else { "./Ans.Dpf.Grpc.bat" }
        Start-Process -FilePath $ToLaunch -ArgumentList "--address 127.0.0.1" -RedirectStandardOutput "log.txt"
      shell: pwsh

    - run: Get-Content -Path $env:SERVER\aisol\bin\winx64\log.txt
      shell: pwsh


