name: "Install package"
description: "Installs the local package using requirements_build.txt and setup.py while 
creating a wheel"
inputs:
  extra-pip-args:
    description: "Args given to pip install command"
    default: ""
    type: string
runs:
  using: "composite"
  steps:
    - name: "Install local package"
      shell: bash
      run: |
        pip install -r requirements/requirements_build.txt
        python setup.py bdist_wheel
        export WHEEL_NAME=`ls dist/*.whl`
        echo ${WHEEL_NAME}
        pip install ${WHEEL_NAME} ${{ inputs.extra-pip-args }}
        cd tests
