name: "Install package"
description: "Installs the local package using the build library."
runs:
  using: "composite"
  steps:
    - name: "Install local package"
      shell: bash
      run: |
        pip install build
        python -m build --wheel
        export WHEEL_NAME=`ls dist/*.whl`
        echo ${WHEEL_NAME}
        pip install ${WHEEL_NAME}
        cd tests
