name: "Push documentation"
description: "Pushes the documentation to the release branch and the doc repo"
inputs:
  PYANSYS_CI_BOT_TOKEN:
    description: "PYANSYS_CI_BOT_TOKEN"
    required: true
  DOC_REPO:
    description: "Name of doc repo to push to, for example: DPF-Post-docs"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Create a commit"
      shell: pwsh
      run: |
        cd docs/build/html
        git init
        git checkout -b $env:GH_DOC_BRANCH
        git config --global user.name "pyansys-ci-bot"
        git config --global user.email "$env:GH_EMAIL"
        New-Item -ItemType file .nojekyll
        git add .
        git commit -m "Documentation generated"
      env:
        GH_DOC_BRANCH: gh-pages
        GH_EMAIL: pyansys.github.bot@ansys.com

    - name: "Push commit to the documentation repository"
      shell: bash
      run: |
        cd docs/build/html
        git remote add origin https://${{inputs.PYANSYS_CI_BOT_TOKEN}}@github.com/pyansys/${{inputs.DOC_REPO}}
        git push -u origin $env:GH_DOC_BRANCH --force
      env:
        GH_DOC_BRANCH: gh-pages
