name: GitHub Actions

on:
  pull_request:
     branches-ignore:
       - '*no-ci*'
  push:
    tags:
      - "*"
    branches:
      - master
      - "release*"

jobs:
  test_windows:
    name: Windows
    runs-on: windows-2019

    env:
      ANSYS_VERSION: 221

    steps:
      - uses: actions/checkout@v2

      - id: install-dpf
        uses: pydpf-actions/install-dpf-server@v0
        with:
          dpf-standalone-TOKEN: ""
          ANSYS_VERSION: ${{env.ANSYS_VERSION}}
